/**
 * مدير المعاجم - Lexicon Manager
 * Integrates all lexicon components
 */
import { RootAnalyzer, WordRoot, RootFamily } from './rootAnalyzer';
import { DerivationGenerator, Derivation, DerivationType, DerivationForm } from './derivationGenerator';
import { LexiconEngine, LexiconEntry, WordType, SearchOptions } from './lexiconEngine';
export interface LexiconAnalysis {
    word: string;
    entry: LexiconEntry | null;
    root: WordRoot | null;
    derivations: Derivation[];
    relatedWords: string[];
    timestamp: number;
}
export interface LexiconSettings {
    autoGenerateDerivations: boolean;
    autoDetectRoot: boolean;
    minConfidenceThreshold: number;
    maxDerivations: number;
}
export declare class LexiconManager {
    private rootAnalyzer;
    private derivationGenerator;
    private lexiconEngine;
    private settings;
    constructor();
    addWord(word: string, type: WordType, definition: string, autoAnalyze?: boolean): LexiconAnalysis;
    analyzeWord(word: string): LexiconAnalysis;
    search(query: string, options?: SearchOptions): LexiconEntry[];
    getWord(word: string): LexiconEntry | null;
    findByRoot(root: string): {
        entries: LexiconEntry[];
        family: RootFamily | null;
        derivations: Derivation[];
    };
    generateDerivation(root: string, type: DerivationType, form?: DerivationForm, meaning?: string): Derivation;
    addExample(word: string, example: string): boolean;
    addSynonym(word: string, synonym: string): boolean;
    addAntonym(word: string, antonym: string): boolean;
    updateSettings(newSettings: Partial<LexiconSettings>): void;
    getSettings(): LexiconSettings;
    getRootAnalyzer(): RootAnalyzer;
    getDerivationGenerator(): DerivationGenerator;
    getLexiconEngine(): LexiconEngine;
    getStatistics(): {
        lexicon: ReturnType<LexiconEngine['getStatistics']>;
        roots: ReturnType<RootAnalyzer['getStatistics']>;
        derivations: ReturnType<DerivationGenerator['getStatistics']>;
    };
    clearAll(): void;
}
