/**
 * Multilingual Lexicon Manager
 * مدير المعاجم متعدد اللغات
 *
 * Unified manager for Arabic and English lexicons
 * مدير موحد للمعاجم العربية والإنجليزية
 */
import { WordRoot, RootFamily } from './rootAnalyzer';
import { Derivation } from './derivationGenerator';
import { EnglishWordRoot, EnglishRootFamily } from './englishRootAnalyzer';
import { EnglishDerivation } from './englishDerivationGenerator';
import { LexiconEntry, WordType, SearchOptions } from './lexiconEngine';
export type SupportedLanguage = 'arabic' | 'english' | 'both';
export interface MultilingualLexiconAnalysis {
    word: string;
    language: SupportedLanguage;
    entry: LexiconEntry | null;
    root: WordRoot | EnglishWordRoot | null;
    derivations: (Derivation | EnglishDerivation)[];
    relatedWords: string[];
    confidence: number;
    timestamp: number;
}
export interface MultilingualLexiconSettings {
    autoGenerateDerivations: boolean;
    autoDetectRoot: boolean;
    autoDetectLanguage: boolean;
    minConfidenceThreshold: number;
    maxDerivations: number;
}
/**
 * Multilingual Lexicon Manager
 * مدير المعاجم متعدد اللغات
 */
export declare class MultilingualLexiconManager {
    private arabicRootAnalyzer;
    private arabicDerivationGenerator;
    private englishRootAnalyzer;
    private englishDerivationGenerator;
    private lexiconEngine;
    private settings;
    constructor(settings?: Partial<MultilingualLexiconSettings>);
    /**
     * Detect language of word
     * كشف لغة الكلمة
     */
    detectLanguage(word: string): SupportedLanguage;
    /**
     * Add word to lexicon
     * إضافة كلمة للمعجم
     */
    addWord(word: string, type: WordType, definition: string, language?: SupportedLanguage): LexiconEntry;
    /**
     * Generate derivations for word
     * توليد اشتقاقات للكلمة
     */
    private generateDerivationsForWord;
    /**
     * Analyze word in any language
     * تحليل كلمة بأي لغة
     */
    analyzeWord(word: string): MultilingualLexiconAnalysis;
    /**
     * Search in lexicon
     * البحث في المعجم
     */
    search(query: string, options?: SearchOptions): LexiconEntry[];
    /**
     * Get word entry
     * الحصول على مدخل الكلمة
     */
    getWord(word: string): LexiconEntry | null;
    /**
     * Get root family (Arabic)
     * الحصول على عائلة الجذر (عربي)
     */
    getArabicRootFamily(root: string): RootFamily | null;
    /**
     * Get root family (English)
     * الحصول على عائلة الجذر (إنجليزي)
     */
    getEnglishRootFamily(root: string): EnglishRootFamily | null;
    /**
     * Get statistics
     * الحصول على الإحصائيات
     */
    getStatistics(): {
        arabic: {
            totalRoots: number;
            totalFamilies: number;
            averageDerivations: number;
        };
        english: {
            totalRoots: number;
            totalFamilies: number;
            averageDerivations: number;
        };
        lexicon: {
            totalEntries: number;
            byLanguage: Record<SupportedLanguage, number>;
        };
    };
    /**
     * Update settings
     * تحديث الإعدادات
     */
    updateSettings(settings: Partial<MultilingualLexiconSettings>): void;
    /**
     * Get current settings
     * الحصول على الإعدادات الحالية
     */
    getSettings(): MultilingualLexiconSettings;
    /**
     * Clear all data
     * مسح جميع البيانات
     */
    clear(): void;
    /**
     * Export lexicon data
     * تصدير بيانات المعجم
     */
    exportData(): {
        entries: LexiconEntry[];
        arabicRoots: number;
        englishRoots: number;
        timestamp: number;
    };
}
/**
 * Global instance for easy access
 * نسخة عامة للوصول السهل
 */
export declare const multilingualLexicon: MultilingualLexiconManager;
